#app
server:
  port: 8080
  
jwt:
  invalidate-time: 172800
  secret: 49f4c3f37b154be1aba6c495fbf97c1b

lynx:
  swagger-open: true  #是否开启swagger (true/false)
  yunpian-apikey: e5049b80e388951b6a209b702bb1d93d

#spring
spring:
  profiles:
    active: test
  devtools:
    restart:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    
#出现错误时, 直接抛出异常
#spring.mvc.throw-exception-if-no-handler-found=true
#不要为我们工程中的资源文件建立映射
#spring.resources.add-mappings=false

#mybatis
mybatis-plus:
  #mapper-locations: classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.helapu.lynx.entity
  typeEnumsPackage: com.helapu.lynx.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      #column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
#logging:
#  level: warn

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKey-id: LTAIsOM28rawLJAn
    accessKey-secret: yks4wtaotu2BtnHqHe8AOs21zsaOsh
    bucket-name: lynxweb
  iot:
    endpoint: 
    accessKey:
    accessSecret:
    
# 电信物联网
telecom:
  platform-ip: 180.101.147.89
  platform-port: 8743
  app-id: 9R9qAKYA8aaIC9BtMbtO0acC5VMa
  app-secret: wW8M8IVPkFJajFQ7dzOmR0rIk8Aa
  
  server:
    port: 8080
    ssl:
      #one-way authentication (server-auth)
      key-store: ./src/main/resources/tomcat.keystore
      key-store-password: 741852963.
      trust-store: ./src/main/resources/tomcat.keystore
      trust-store-password: 741852963.
      client-auth: need    
    
#    #the value of newCaFile and newClientCertFile should not be the same as "ca.jks" or "outgoing.CertwithKey.pkcs12"
#    newCaFile: 
#    newCaPassword: 
#    newClientCertFile: 
#    newClientCertPassword: 
#    #hostNameVerify default value is true, true means setting STRICT_HOSTNAME_VERIFIER, false means setting ALLOW_ALL_HOSTNAME_VERIFIER 
#    hostNameVerify: 
#    
#    test: 50FE6401E867A34BD533FE67BB85EDABFED62CEA9D8E3F5516E7B48D01F21A5F
#

# 有赞商城开放平台
youzan:
  client-id: 578dcba00bc300539b
  client-secret: d133449a0b11d555fd8c9ca5a0ba61de
  grant-type: silent
  kdt-id: 41119237

                       